# Generated by Django 4.0.3 on 2022-04-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyvacancy',
            name='link',
            field=models.URLField(default='test', max_length=400, null=True),
        ),
    ]
