# Generated by Django 4.0.3 on 2022-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applyvacancy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyvacancy',
            name='date',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='applyvacancy',
            name='time',
            field=models.TimeField(max_length=400, null=True),
        ),
    ]
