# Generated by Django 4.0.3 on 2022-05-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_postjob_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyvacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.companyegistration'),
        ),
    ]
